#ddev-generated
services:
  typesense:
    container_name: ddev-${DDEV_SITENAME}-typesense
    hostname: ${DDEV_SITENAME}-typesense
    image: typesense/typesense:29.0
    command: tail -f /dev/null
    networks: [default, ddev_default]
    restart: "yes"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=writeable-api
      
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "./typesense:/data"
